// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClYQMoFG_19uc-r0vX8bJ9DWVlaEJNfj4',
    appId: '1:364379889376:web:67c526725d08c6e1d7fa85',
    messagingSenderId: '364379889376',
    projectId: 'shop-local-4d81d',
    authDomain: 'shop-local-4d81d.firebaseapp.com',
    storageBucket: 'shop-local-4d81d.firebasestorage.app',
    measurementId: 'G-1D23Q3NBL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXqhJOYvIO61sW76lnii_eRlsYhIFzwDc',
    appId: '1:364379889376:android:ba189eade762ebd4d7fa85',
    messagingSenderId: '364379889376',
    projectId: 'shop-local-4d81d',
    storageBucket: 'shop-local-4d81d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZxQiqY9LgpUbFg25DbU4MuHayrWoQvp8',
    appId: '1:364379889376:ios:0668becda9c73b46d7fa85',
    messagingSenderId: '364379889376',
    projectId: 'shop-local-4d81d',
    storageBucket: 'shop-local-4d81d.firebasestorage.app',
    iosBundleId: 'com.example.shopLocal',
  );
}
