import 'package:intl_phone_field/countries.dart';

const List<Country> allCountries = [
  // --- الدول العربية والخليجية ---
  Country(code: 'SA', name: 'المملكة العربية السعودية', nameTranslations: {}, flag: '🇸🇦', dialCode: '966', minLength: 9, maxLength: 9),
  Country(code: 'AE', name: 'الإمارات العربية المتحدة', nameTranslations: {}, flag: '🇦🇪', dialCode: '971', minLength: 9, maxLength: 9),
  Country(code: 'KW', name: 'الكويت', nameTranslations: {}, flag: '🇰🇼', dialCode: '965', minLength: 8, maxLength: 8),
  Country(code: 'QA', name: 'قطر', nameTranslations: {}, flag: '🇶🇦', dialCode: '974', minLength: 8, maxLength: 8),
  Country(code: 'BH', name: 'البحرين', nameTranslations: {}, flag: '🇧🇭', dialCode: '973', minLength: 8, maxLength: 8),
  Country(code: 'OM', name: 'عُمان', nameTranslations: {}, flag: '🇴🇲', dialCode: '968', minLength: 8, maxLength: 8),
  Country(code: 'EG', name: 'مصر', nameTranslations: {}, flag: '🇪🇬', dialCode: '20', minLength: 10, maxLength: 10),
  Country(code: 'JO', name: 'الأردن', nameTranslations: {}, flag: '🇯🇴', dialCode: '962', minLength: 9, maxLength: 9),
  Country(code: 'PS', name: 'فلسطين', nameTranslations: {}, flag: '🇵🇸', dialCode: '970', minLength: 9, maxLength: 9),
  Country(code: 'IQ', name: 'العراق', nameTranslations: {}, flag: '🇮🇶', dialCode: '964', minLength: 10, maxLength: 10),
  Country(code: 'LB', name: 'لبنان', nameTranslations: {}, flag: '🇱🇧', dialCode: '961', minLength: 7, maxLength: 8),
  Country(code: 'SY', name: 'سوريا', nameTranslations: {}, flag: '🇸🇾', dialCode: '963', minLength: 9, maxLength: 9),
  Country(code: 'YE', name: 'اليمن', nameTranslations: {}, flag: '🇾🇪', dialCode: '967', minLength: 9, maxLength: 9),
  Country(code: 'MA', name: 'المغرب', nameTranslations: {}, flag: '🇲🇦', dialCode: '212', minLength: 9, maxLength: 9),
  Country(code: 'DZ', name: 'الجزائر', nameTranslations: {}, flag: '🇩🇿', dialCode: '213', minLength: 9, maxLength: 9),
  Country(code: 'TN', name: 'تونس', nameTranslations: {}, flag: '🇹🇳', dialCode: '216', minLength: 8, maxLength: 8),
  Country(code: 'LY', name: 'ليبيا', nameTranslations: {}, flag: '🇱🇾', dialCode: '218', minLength: 9, maxLength: 9),
  Country(code: 'SD', name: 'السودان', nameTranslations: {}, flag: '🇸🇩', dialCode: '249', minLength: 9, maxLength: 9),
  Country(code: 'MR', name: 'موريتانيا', nameTranslations: {}, flag: '🇲🇷', dialCode: '222', minLength: 8, maxLength: 8),
  Country(code: 'SO', name: 'الصومال', nameTranslations: {}, flag: '🇸🇴', dialCode: '252', minLength: 9, maxLength: 9),
  Country(code: 'DJ', name: 'جيبوتي', nameTranslations: {}, flag: '🇩🇯', dialCode: '253', minLength: 8, maxLength: 8),
  Country(code: 'KM', name: 'جزر القمر', nameTranslations: {}, flag: '🇰🇲', dialCode: '269', minLength: 7, maxLength: 7),

  // --- دول أفريقيا المحيطة ---
  Country(code: 'TD', name: 'تشاد', nameTranslations: {}, flag: '🇹🇩', dialCode: '235', minLength: 8, maxLength: 8),
  Country(code: 'NER', name: 'النيجر', nameTranslations: {}, flag: '🇳🇪', dialCode: '227', minLength: 8, maxLength: 8),
  Country(code: 'ML', name: 'مالي', nameTranslations: {}, flag: '🇲🇱', dialCode: '223', minLength: 8, maxLength: 8),
  Country(code: 'SEN', name: 'السنغال', nameTranslations: {}, flag: '🇸🇳', dialCode: '221', minLength: 9, maxLength: 9),
  Country(code: 'NG', name: 'نيجيريا', nameTranslations: {}, flag: '🇳🇬', dialCode: '234', minLength: 10, maxLength: 11),
  Country(code: 'GH', name: 'غانا', nameTranslations: {}, flag: '🇬🇭', dialCode: '233', minLength: 9, maxLength: 9),
  Country(code: 'ET', name: 'إثيوبيا', nameTranslations: {}, flag: '🇪🇹', dialCode: '251', minLength: 9, maxLength: 9),
  Country(code: 'KE', name: 'كينيا', nameTranslations: {}, flag: '🇰🇪', dialCode: '254', minLength: 9, maxLength: 9),
  Country(code: 'TZ', name: 'تنزانيا', nameTranslations: {}, flag: '🇹🇿', dialCode: '255', minLength: 9, maxLength: 9),
  Country(code: 'UG', name: 'أوغندا', nameTranslations: {}, flag: '🇺🇬', dialCode: '256', minLength: 9, maxLength: 9),
  Country(code: 'ZA', name: 'جنوب أفريقيا', nameTranslations: {}, flag: '🇿🇦', dialCode: '27', minLength: 9, maxLength: 9),

  // --- دول أوروبا ---
  Country(code: 'GB', name: 'المملكة المتحدة (بريطانيا)', nameTranslations: {}, flag: '🇬🇧', dialCode: '44', minLength: 10, maxLength: 10),
  Country(code: 'DE', name: 'ألمانيا', nameTranslations: {}, flag: '🇩🇪', dialCode: '49', minLength: 10, maxLength: 11),
  Country(code: 'FR', name: 'فرنسا', nameTranslations: {}, flag: '🇫🇷', dialCode: '33', minLength: 9, maxLength: 9),
  Country(code: 'IT', name: 'إيطاليا', nameTranslations: {}, flag: '🇮🇹', dialCode: '39', minLength: 10, maxLength: 10),
  Country(code: 'ES', name: 'إسبانيا', nameTranslations: {}, flag: '🇪🇸', dialCode: '34', minLength: 9, maxLength: 9),
  Country(code: 'NL', name: 'هولندا', nameTranslations: {}, flag: '🇳🇱', dialCode: '31', minLength: 9, maxLength: 9),
  Country(code: 'BE', name: 'بلجيكا', nameTranslations: {}, flag: '🇧🇪', dialCode: '32', minLength: 9, maxLength: 9),
  Country(code: 'CH', name: 'سويسرا', nameTranslations: {}, flag: '🇨🇭', dialCode: '41', minLength: 9, maxLength: 9),
  Country(code: 'AT', name: 'النمسا', nameTranslations: {}, flag: '🇦🇹', dialCode: '43', minLength: 10, maxLength: 13),
  Country(code: 'SE', name: 'السويد', nameTranslations: {}, flag: '🇸🇪', dialCode: '46', minLength: 9, maxLength: 9),
  Country(code: 'NO', name: 'النرويج', nameTranslations: {}, flag: '🇳🇴', dialCode: '47', minLength: 8, maxLength: 8),
  Country(code: 'DK', name: 'الدنمارك', nameTranslations: {}, flag: '🇩🇰', dialCode: '45', minLength: 8, maxLength: 8),
  Country(code: 'FI', name: 'فنلندا', nameTranslations: {}, flag: '🇫🇮', dialCode: '358', minLength: 9, maxLength: 10),
  Country(code: 'IE', name: 'أيرلندا', nameTranslations: {}, flag: '🇮🇪', dialCode: '353', minLength: 9, maxLength: 9),
  Country(code: 'PT', name: 'البرتغال', nameTranslations: {}, flag: '🇵🇹', dialCode: '351', minLength: 9, maxLength: 9),
  Country(code: 'GR', name: 'اليونان', nameTranslations: {}, flag: '🇬🇷', dialCode: '30', minLength: 10, maxLength: 10),
  Country(code: 'RU', name: 'روسيا', nameTranslations: {}, flag: '🇷🇺', dialCode: '7', minLength: 10, maxLength: 10),
  Country(code: 'UA', name: 'أوكرانيا', nameTranslations: {}, flag: '🇺🇦', dialCode: '380', minLength: 9, maxLength: 9),
  Country(code: 'PL', name: 'بولندا', nameTranslations: {}, flag: '🇵🇱', dialCode: '48', minLength: 9, maxLength: 9),
  Country(code: 'RO', name: 'رومانيا', nameTranslations: {}, flag: '🇷🇴', dialCode: '40', minLength: 9, maxLength: 9),

  // --- قارة أمريكا الشمالية والجنوبية ---
  Country(code: 'US', name: 'الولايات المتحدة الأمريكية', nameTranslations: {}, flag: '🇺🇸', dialCode: '1', minLength: 10, maxLength: 10),
  Country(code: 'CA', name: 'كندا', nameTranslations: {}, flag: '🇨🇦', dialCode: '1', minLength: 10, maxLength: 10),
  Country(code: 'MX', name: 'المكسيك', nameTranslations: {}, flag: '🇲🇽', dialCode: '52', minLength: 10, maxLength: 10),
  Country(code: 'BR', name: 'البرازيل', nameTranslations: {}, flag: '🇧🇷', dialCode: '55', minLength: 10, maxLength: 11),
  Country(code: 'AR', name: 'الأرجنتين', nameTranslations: {}, flag: '🇦🇷', dialCode: '54', minLength: 10, maxLength: 11),
  Country(code: 'CO', name: 'كولومبيا', nameTranslations: {}, flag: '🇨🇴', dialCode: '57', minLength: 10, maxLength: 10),
  Country(code: 'CL', name: 'تشيلي', nameTranslations: {}, flag: '🇨🇱', dialCode: '56', minLength: 9, maxLength: 9),

  // --- قارة آسيا وأوقيانوسيا ---
  Country(code: 'TR', name: 'تركيا', nameTranslations: {}, flag: '🇹🇷', dialCode: '90', minLength: 10, maxLength: 10),
  Country(code: 'CN', name: 'الصين', nameTranslations: {}, flag: '🇨🇳', dialCode: '86', minLength: 11, maxLength: 11),
  Country(code: 'JP', name: 'اليابان', nameTranslations: {}, flag: '🇯🇵', dialCode: '81', minLength: 10, maxLength: 10),
  Country(code: 'KR', name: 'كوريا الجنوبية', nameTranslations: {}, flag: '🇰🇷', dialCode: '82', minLength: 9, maxLength: 10),
  Country(code: 'IN', name: 'الهند', nameTranslations: {}, flag: '🇮🇳', dialCode: '91', minLength: 10, maxLength: 10),
  Country(code: 'PK', name: 'باكستان', nameTranslations: {}, flag: '🇵🇰', dialCode: '92', minLength: 10, maxLength: 10),
  Country(code: 'BD', name: 'بنجلاديش', nameTranslations: {}, flag: '🇧🇩', dialCode: '880', minLength: 10, maxLength: 10),
  Country(code: 'ID', name: 'إندونيسيا', nameTranslations: {}, flag: '🇮🇩', dialCode: '62', minLength: 9, maxLength: 12),
  Country(code: 'MY', name: 'ماليزيا', nameTranslations: {}, flag: '🇲🇾', dialCode: '60', minLength: 9, maxLength: 11),
  Country(code: 'PH', name: 'الفلبين', nameTranslations: {}, flag: '🇵🇭', dialCode: '63', minLength: 10, maxLength: 10),
  Country(code: 'SG', name: 'سنغافورة', nameTranslations: {}, flag: '🇸🇬', dialCode: '65', minLength: 8, maxLength: 8),
  Country(code: 'TH', name: 'تايلاند', nameTranslations: {}, flag: '🇹🇭', dialCode: '66', minLength: 9, maxLength: 9),
  Country(code: 'VN', name: 'فيتنام', nameTranslations: {}, flag: '🇻🇳', dialCode: '84', minLength: 9, maxLength: 10),
  Country(code: 'AU', name: 'أستراليا', nameTranslations: {}, flag: '🇦🇺', dialCode: '61', minLength: 9, maxLength: 9),
  Country(code: 'NZ', name: 'نيوزيلندا', nameTranslations: {}, flag: '🇳🇿', dialCode: '64', minLength: 8, maxLength: 10),
  Country(code: 'IR', name: 'إيران', nameTranslations: {}, flag: '🇮🇷', dialCode: '98', minLength: 10, maxLength: 10),
  Country(code: 'AF', name: 'أفغانستان', nameTranslations: {}, flag: '🇦🇫', dialCode: '93', minLength: 9, maxLength: 9),
  Country(code: 'AZ', name: 'أذربيجان', nameTranslations: {}, flag: '🇦🇿', dialCode: '994', minLength: 9, maxLength: 9),
  Country(code: 'GE', name: 'جورجيا', nameTranslations: {}, flag: '🇬🇪', dialCode: '995', minLength: 9, maxLength: 9),
  Country(code: 'KZ', name: 'كازاخستان', nameTranslations: {}, flag: '🇰🇿', dialCode: '7', minLength: 10, maxLength: 10),
  Country(code: 'UZ', name: 'أوزبكستان', nameTranslations: {}, flag: '🇺🇿', dialCode: '998', minLength: 9, maxLength: 9),

  // --- بقية دول العالم المتبقية لضمان الشمولية العظمى (أوروبا الشرقية، الكاريبي، وأفريقيا الوسطى) ---
  Country(code: 'AL', name: 'ألبانيا', nameTranslations: {}, flag: '🇦🇱', dialCode: '355', minLength: 9, maxLength: 9),
  Country(code: 'AD', name: 'أندورا', nameTranslations: {}, flag: '🇦🇩', dialCode: '376', minLength: 6, maxLength: 6),
  Country(code: 'AO', name: 'أنغولا', nameTranslations: {}, flag: '🇦🇴', dialCode: '244', minLength: 9, maxLength: 9),
  Country(code: 'AG', name: 'أنتيغوا وبربودا', nameTranslations: {}, flag: '🇦🇬', dialCode: '1', minLength: 10, maxLength: 10),
  Country(code: 'AM', name: 'أرمينيا', nameTranslations: {}, flag: '🇦🇲', dialCode: '374', minLength: 8, maxLength: 8),
  Country(code: 'AW', name: 'أروبا', nameTranslations: {}, flag: '🇦🇼', dialCode: '297', minLength: 7, maxLength: 7),
  Country(code: 'BS', name: 'جزر البهاما', nameTranslations: {}, flag: '🇧🇸', dialCode: '1', minLength: 10, maxLength: 10),
  Country(code: 'BB', name: 'باربادوس', nameTranslations: {}, flag: '🇧🇧', dialCode: '1', minLength: 10, maxLength: 10),
  Country(code: 'BY', name: 'بيلاروسيا', nameTranslations: {}, flag: '🇧🇾', dialCode: '375', minLength: 9, maxLength: 9),
  Country(code: 'BZ', name: 'بليز', nameTranslations: {}, flag: '🇧🇿', dialCode: '501', minLength: 7, maxLength: 7),
  Country(code: 'BJ', name: 'بنين', nameTranslations: {}, flag: '🇧🇯', dialCode: '229', minLength: 8, maxLength: 8),
  Country(code: 'BM', name: 'برمودا', nameTranslations: {}, flag: '🇧🇲', dialCode: '1', minLength: 10, maxLength: 10),
  Country(code: 'BT', name: 'بوتان', nameTranslations: {}, flag: '🇧🇹', dialCode: '975', minLength: 8, maxLength: 8),
  Country(code: 'BO', name: 'بوليفيا', nameTranslations: {}, flag: '🇧🇴', dialCode: '591', minLength: 8, maxLength: 8),
  Country(code: 'BA', name: 'البوسنة والهرسك', nameTranslations: {}, flag: '🇧🇦', dialCode: '387', minLength: 8, maxLength: 9),
  Country(code: 'BW', name: 'بوتسوانا', nameTranslations: {}, flag: '🇧🇼', dialCode: '267', minLength: 7, maxLength: 8),
  Country(code: 'BN', name: 'بروناي', nameTranslations: {}, flag: '🇧🇳', dialCode: '673', minLength: 7, maxLength: 7),
  Country(code: 'BG', name: 'بلغاريا', nameTranslations: {}, flag: '🇧🇬', dialCode: '359', minLength: 8, maxLength: 9),
  Country(code: 'BF', name: 'بوركينا فاسو', nameTranslations: {}, flag: '🇧🇫', dialCode: '226', minLength: 8, maxLength: 8),
  Country(code: 'BI', name: 'بوروندي', nameTranslations: {}, flag: '🇧🇮', dialCode: '257', minLength: 8, maxLength: 8),
  Country(code: 'KH', name: 'كمبوديا', nameTranslations: {}, flag: '🇰🇭', dialCode: '855', minLength: 8, maxLength: 9),
  Country(code: 'CM', name: 'الكاميرون', nameTranslations: {}, flag: '🇨🇲', dialCode: '237', minLength: 9, maxLength: 9),
  Country(code: 'CV', name: 'الرأس الأخضر', nameTranslations: {}, flag: '🇨🇻', dialCode: '238', minLength: 7, maxLength: 7),
  Country(code: 'CF', name: 'جمهورية أفريقيا الوسطى', nameTranslations: {}, flag: '🇨🇫', dialCode: '236', minLength: 8, maxLength: 8),
  Country(code: 'CG', name: 'جمهورية الكونغو', nameTranslations: {}, flag: '🇨🇬', dialCode: '242', minLength: 9, maxLength: 9),
  Country(code: 'CD', name: 'جمهورية الكونغو الديمقراطية', nameTranslations: {}, flag: '🇨🇩', dialCode: '243', minLength: 9, maxLength: 9),
  Country(code: 'CR', name: 'كوستاريكا', nameTranslations: {}, flag: '🇨🇷', dialCode: '506', minLength: 8, maxLength: 8),
  Country(code: 'CI', name: 'ساحل العاج', nameTranslations: {}, flag: '🇨🇮', dialCode: '225', minLength: 10, maxLength: 10),
  Country(code: 'HR', name: 'كرواتيا', nameTranslations: {}, flag: '🇭🇷', dialCode: '385', minLength: 8, maxLength: 9),
  Country(code: 'CU', name: 'كوبا', nameTranslations: {}, flag: '🇨🇺', dialCode: '53', minLength: 8, maxLength: 8),
  Country(code: 'CY', name: 'قبرص', nameTranslations: {}, flag: '🇨🇾', dialCode: '357', minLength: 8, maxLength: 8),
  Country(code: 'CZ', name: 'جمهورية التشيك', nameTranslations: {}, flag: '🇨🇿', dialCode: '420', minLength: 9, maxLength: 9),
  Country(code: 'DO', name: 'جمهورية الدومينيكان', nameTranslations: {}, flag: '🇩🇴', dialCode: '1', minLength: 10, maxLength: 10),
  Country(code: 'EC', name: 'الإكوادور', nameTranslations: {}, flag: '🇪🇨', dialCode: '593', minLength: 9, maxLength: 9),
  Country(code: 'SV', name: 'السلفادور', nameTranslations: {}, flag: '🇸🇻', dialCode: '503', minLength: 8, maxLength: 8),
  Country(code: 'GQ', name: 'غينيا الاستوائية', nameTranslations: {}, flag: '🇬🇶', dialCode: '240', minLength: 9, maxLength: 9),
  Country(code: 'ER', name: 'إريتريا', nameTranslations: {}, flag: '🇪🇷', dialCode: '291', minLength: 7, maxLength: 7),
  Country(code: 'EE', name: 'إستونيا', nameTranslations: {}, flag: '🇪🇪', dialCode: '372', minLength: 7, maxLength: 8),
  Country(code: 'FJ', name: 'فيجي', nameTranslations: {}, flag: '🇫🇯', dialCode: '679', minLength: 7, maxLength: 7),
  Country(code: 'GA', name: 'الغابون', nameTranslations: {}, flag: '🇬🇦', dialCode: '241', minLength: 7, maxLength: 8),
  Country(code: 'GM', name: 'غامبيا', nameTranslations: {}, flag: '🇬🇲', dialCode: '220', minLength: 7, maxLength: 7),
  Country(code: 'GH', name: 'غينيا', nameTranslations: {}, flag: '🇬🇳', dialCode: '224', minLength: 9, maxLength: 9),
  Country(code: 'GY', name: 'غويانا', nameTranslations: {}, flag: '🇬🇾', dialCode: '592', minLength: 7, maxLength: 7),
  Country(code: 'HT', name: 'هايتي', nameTranslations: {}, flag: '🇭🇹', dialCode: '509', minLength: 8, maxLength: 8),
  Country(code: 'HN', name: 'هندوراس', nameTranslations: {}, flag: '🇭🇳', dialCode: '504', minLength: 8, maxLength: 8),
  Country(code: 'HU', name: 'المجر (هنغاريا)', nameTranslations: {}, flag: '🇭🇺', dialCode: '36', minLength: 9, maxLength: 9),
  Country(code: 'IS', name: 'آيسلندا', nameTranslations: {}, flag: '🇮🇸', dialCode: '354', minLength: 7, maxLength: 7),
  Country(code: 'JM', name: 'جامايكا', nameTranslations: {}, flag: '🇯🇲', dialCode: '1', minLength: 10, maxLength: 10),
  Country(code: 'LA', name: 'لاوس', nameTranslations: {}, flag: '🇱🇦', dialCode: '856', minLength: 10, maxLength: 10),
  Country(code: 'LV', name: 'لاتفيا', nameTranslations: {}, flag: '🇱🇻', dialCode: '371', minLength: 8, maxLength: 8),
  Country(code: 'LR', name: 'ليبيريا', nameTranslations: {}, flag: '🇱🇷', dialCode: '231', minLength: 7, maxLength: 8),
  Country(code: 'LT', name: 'ليتوانيا', nameTranslations: {}, flag: '🇱🇹', dialCode: '370', minLength: 8, maxLength: 8),
  Country(code: 'LU', name: 'لوكسمبورغ', nameTranslations: {}, flag: '🇱🇺', dialCode: '352', minLength: 9, maxLength: 9),
  Country(code: 'MK', name: 'مقدونيا الشمالية', nameTranslations: {}, flag: '🇲🇰', dialCode: '389', minLength: 8, maxLength: 8),
  Country(code: 'MG', name: 'مدغشقر', nameTranslations: {}, flag: '🇲🇬', dialCode: '261', minLength: 9, maxLength: 9),
  Country(code: 'MW', name: 'ملاوي', nameTranslations: {}, flag: '🇲🇼', dialCode: '265', minLength: 7, maxLength: 9),
  Country(code: 'MV', name: 'جزر المالديف', nameTranslations: {}, flag: '🇲🇻', dialCode: '960', minLength: 7, maxLength: 7),
  Country(code: 'MT', name: 'مالطا', nameTranslations: {}, flag: '🇲🇹', dialCode: '356', minLength: 8, maxLength: 8),
  Country(code: 'MU', name: 'موريشيوس', nameTranslations: {}, flag: '🇲🇺', dialCode: '230', minLength: 7, maxLength: 8),
  Country(code: 'MD', name: 'مولدوفا', nameTranslations: {}, flag: '🇲🇩', dialCode: '373', minLength: 8, maxLength: 8),
  Country(code: 'MN', name: 'منغوليا', nameTranslations: {}, flag: '🇲🇳', dialCode: '976', minLength: 8, maxLength: 8),
  Country(code: 'ME', name: 'الجبل الأسود', nameTranslations: {}, flag: '🇲🇪', dialCode: '382', minLength: 8, maxLength: 8),
  Country(code: 'MZ', name: 'موزمبيق', nameTranslations: {}, flag: '🇲🇿', dialCode: '258', minLength: 8, maxLength: 9),
  Country(code: 'MM', name: 'ميانمار (بورما)', nameTranslations: {}, flag: '🇲🇲', dialCode: '95', minLength: 8, maxLength: 10),
  Country(code: 'NA', name: 'ناميبيا', nameTranslations: {}, flag: '🇳🇦', dialCode: '264', minLength: 7, maxLength: 9),
  Country(code: 'NP', name: 'نيبال', nameTranslations: {}, flag: '🇳🇵', dialCode: '977', minLength: 10, maxLength: 10),
  Country(code: 'NI', name: 'نيكاراجوا', nameTranslations: {}, flag: '🇳🇮', dialCode: '505', minLength: 8, maxLength: 8),
  Country(code: 'PA', name: 'بنما', nameTranslations: {}, flag: '🇵🇦', dialCode: '507', minLength: 7, maxLength: 8),
  Country(code: 'PG', name: 'بابوا غينيا الجديدة', nameTranslations: {}, flag: '🇵🇬', dialCode: '675', minLength: 8, maxLength: 8),
  Country(code: 'PY', name: 'باراغواي', nameTranslations: {}, flag: '🇵🇾', dialCode: '595', minLength: 9, maxLength: 9),
  Country(code: 'PE', name: 'بيرو', nameTranslations: {}, flag: '🇵🇪', dialCode: '51', minLength: 9, maxLength: 9),
  Country(code: 'RW', name: 'رواندا', nameTranslations: {}, flag: '🇷🇼', dialCode: '250', minLength: 9, maxLength: 9),
  Country(code: 'RS', name: 'صربيا', nameTranslations: {}, flag: '🇷🇸', dialCode: '381', minLength: 8, maxLength: 9),
  Country(code: 'SL', name: 'سيراليون', nameTranslations: {}, flag: '🇸🇱', dialCode: '232', minLength: 8, maxLength: 8),
  Country(code: 'SK', name: 'سلوفاكيا', nameTranslations: {}, flag: '🇸🇰', dialCode: '421', minLength: 9, maxLength: 9),
  Country(code: 'SI', name: 'سلوفينيا', nameTranslations: {}, flag: '🇸🇮', dialCode: '386', minLength: 8, maxLength: 8),
  Country(code: 'LK', name: 'سريلانكا', nameTranslations: {}, flag: '🇱🇰', dialCode: '94', minLength: 9, maxLength: 9),
  Country(code: 'SZ', name: 'إسواتيني (سوازيلاند)', nameTranslations: {}, flag: '🇸🇿', dialCode: '268', minLength: 7, maxLength: 7),
  Country(code: 'TG', name: 'توغو', nameTranslations: {}, flag: '🇹🇬', dialCode: '228', minLength: 8, maxLength: 8),
  Country(code: 'TT', name: 'ترينيداد وتوباغو', nameTranslations: {}, flag: '🇹🇹', dialCode: '1', minLength: 10, maxLength: 10),
  Country(code: 'UY', name: 'أوروغواي', nameTranslations: {}, flag: '🇺🇾', dialCode: '598', minLength: 8, maxLength: 8),
  Country(code: 'VE', name: 'فنزويلا', nameTranslations: {}, flag: '🇻🇪', dialCode: '58', minLength: 10, maxLength: 10),
  Country(code: 'ZM', name: 'زامبيا', nameTranslations: {}, flag: '🇿🇲', dialCode: '260', minLength: 9, maxLength: 9),
  Country(code: 'ZW', name: 'زيمبابوي', nameTranslations: {}, flag: '🇿🇼', dialCode: '263', minLength: 9, maxLength: 9),
];